/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export enum AutoFillType {
    UNSPECIFIED = 0,
    PASSWORD = 1,
    USER_NAME = 2,
    NEW_PASSWORD = 3,
    FULL_STREET_ADDRESS = 4,
    HOUSE_NUMBER = 5,
    DISTRICT_ADDRESS = 6,
    CITY_ADDRESS = 7,
    PROVINCE_ADDRESS = 8,
    COUNTRY_ADDRESS = 9,
    PERSON_FULL_NAME = 10,
    PERSON_LAST_NAME = 11,
    PERSON_FIRST_NAME = 12,
    PHONE_NUMBER = 13,
    PHONE_COUNTRY_CODE = 14,
    FULL_PHONE_NUMBER = 15,
    EMAIL_ADDRESS = 16,
    BANK_CARD_NUMBER = 17,
    ID_CARD_NUMBER = 18,
    NICKNAME = 24,
    DETAIL_INFO_WITHOUT_STREET = 25,
    FORMAT_ADDRESS = 26,
    PASSPORT_NUMBER = 27,
    VALIDITY = 28,
    ISSUE_AT = 29,
    ORGANIZATION = 30,
    TAX_ID = 31,
    ADDRESS_CITY_AND_STATE = 32,
    FLIGHT_NUMBER = 33,
    LICENSE_NUMBER = 34,
    LICENSE_FILE_NUMBER = 35,
    LICENSE_PLATE = 36,
    ENGINE_NUMBER = 37,
    LICENSE_CHASSIS_NUMBER = 38
}